name: Demonstrate esbuild_deno_loader Bug
on:
  push:
    branches:
      - "main"

jobs:
  demo-issue:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.39.0

      - name: run esbuild
        run: deno task build
